### ISSUE TITLE
License regkey parameter missing for BYOL license type

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-aws-cloudformation-v2#13]
## Do you already have an issue opened with F5 support?
No

## Description
User wants to deploy BYOL license type. Current example does not ask for a license regkey. There is nothing in runtime init example yaml files for a rendered regkey. The example yaml files have hard coded reg keys of AAAAA-BBBBB-CCCCC-DDDDD-EEEE.

## Template
https://github.com/F5Networks/f5-aws-cloudformation-v2/tree/main/examples/quickstart

## Severity Level
2

**Comment by JeffGiroux** [comment]
Suggest to make a license REG_KEY runtime parameter. Also need to modify parameters in parent template to accept reg key parameter.

runtime init config example
```
          My_License:
            class: License
            licenseType: regKey
            regKey: '{{{REG_KEY}}}'
```

quickstart-parameters.json
```
  {
    "ParameterKey": "regKey",
    "ParameterValue": ""
  },
```

Also, parent template needs to take that input when calling BIG-IP nested template.

quickstart.yml
```
  BigipStandalone:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.amazonaws.com/${artifactLocation}modules/bigip-standalone/bigip-standalone.yaml'
        - S3Region: !Ref 's3BucketRegion'
          S3Bucket: !Ref 's3BucketName'
      Parameters:
        regKey: !Ref 'regKey'
```
